POST http://localhost:3000/descartes HTTP/1.1
content-type: application/json

{

    "userId" : 1,
    "machineId" : 1
                
}

### Ler todos descartes
GET http://localhost:3000/descartes HTTP/1.1
Content-Type: aplication/json
