### Criando um usuário
POST http://localhost:3000/enterprises HTTP/1.1
content-type: application/json

{
   
    "cnpj" : "99.994.999/9999-99",
    "adress" : "Rua",
    "area" : "Reciclagem",
    "name" : "gio",
    "urlImage" :"teste",
    "isActive" : true
}

### ler todos usuarios
GET http://localhost:3000/enterprises HTTP/1.1
content-type: application/json

### Ler usuarios

GET http://localhost:3000/enterprises?area=Reciclagem HTTP/1.1
content-type: application/json

###Ler empresa pelo id

GET http://localhost:3000/enterprises/1
content-type: application/json

### Delete
DELETE  http://localhost:3000/enterprises/3
content-type: application/json

### Atualizar usuario pelo id

PUT   http://localhost:3000/enterprises/4
content-type: application/json

{
    "adress" : "Episcopal",
    "area" : "Limpeza",
    "cnpj" : "99.995.999/9999-99",
    "name" : "gio",
    "urlImage" :"test",
    "isActive" : true
}