
POST http://localhost:3000/machines HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "name": "Máquina 2",
    "status": "Ativa",
    "enterpriseId": 1,
    "amoutn": 50.0
}

###
GET http://localhost:3000/machines HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/machines?name=Máquina HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/machines/1 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/machines/2 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/machines/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Máquina 123 Atualizada",
    "status": "Inativa",
    "enterpriseId": 1
}