POST http://localhost:3000/materiais HTTP/1.1
content-type: application/json

{
    "name": "Tijolo",
    "type": "Pedra",
    "pollutionLevel": 5,
    "weight": 1.5,
    "rewardPoints": 2000,
    "amount": 21
}

### Ler todos materiais
GET http://localhost:3000/materiais HTTP/1.1
Content-Type: aplication/json

### Filtra Materiais

GET http://localhost:3000/materiais?nome=Ti HTTP/1.1
Content-Type: aplication/json